
general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
opacity = 0.95
# blur = true
dynamic_title = true
decorations = "Buttonless"
padding = { x = 4, y = 4 }

[window.dimensions]
columns = 90
lines = 50

[font]
size = 17.0

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[bell]
animation = "EaseOutExpo"
duration = 100

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\\u0000-\\u001F\\u007F-\\u009F<>\\\"\\s{-}\\^⟨⟩`]+"
command = "open"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "Shift"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"


[keyboard]
bindings = [
  { key = "J", mods = "Control|Option|Shift|Command", chars = "\u001b[25~" }, # F13
  { key = "K", mods = "Control|Option|Shift|Command", chars = "\u001b[26~" }, # F14
  # { key = "D", mods = "Control|Option|Shift|Command", chars = "\u001b[28~" }, # F15
  # { key = "F", mods = "Control|Option|Shift|Command", chars = "\u001b[29~" }, # F16
  # { key = "G", mods = "Control|Option|Shift|Command", chars = "\u001b[31~" }, # F17
  # { key = "H", mods = "Control|Option|Shift|Command", chars = "\u001b[32~" }, # F18
  # { key = "J", mods = "Control|Option|Shift|Command", chars = "\u001b[33~" }, # F19
  # { key = "K", mods = "Control|Option|Shift|Command", chars = "\u001b[34~" }, # F20
  # { key = "L", mods = "Control|Option|Shift|Command", chars = "\u001b[42~" }, # F21
  # { key = "Q", mods = "Control|Option|Shift|Command", chars = "\u001b[43~" }, # F22
  # { key = "W", mods = "Control|Option|Shift|Command", chars = "\u001b[44~" }, # F23
  # { key = "E", mods = "Control|Option|Shift|Command", chars = "\u001b[45~" }  # F24
]
